import GalleryTemplate from "./GalleryTemplate";

const imagePaths = [
  `${import.meta.env.BASE_URL}/images/animals/DSC_0031.JPG`,
  `${import.meta.env.BASE_URL}/images/animals/DSC_0036.JPG`,
  `${import.meta.env.BASE_URL}/images/animals/DSC_0038.JPG`,
  `${import.meta.env.BASE_URL}/images/animals/DSC_0063.JPG`,
  `${import.meta.env.BASE_URL}/images/animals/DSC_0064.JPG`,
  `${import.meta.env.BASE_URL}/images/animals/DSC_0067.JPG`,
  `${import.meta.env.BASE_URL}/images/animals/DSC_0124.JPG`,
  `${import.meta.env.BASE_URL}/images/animals/DSC_0159.JPG`,
  `${import.meta.env.BASE_URL}/images/animals/DSC_0176.JPG`,
  `${import.meta.env.BASE_URL}/images/animals/DSC_0178.JPG`,
  `${import.meta.env.BASE_URL}/images/animals/DSC_0244.JPG`,
  `${import.meta.env.BASE_URL}/images/animals/DSC_0286.JPG`,
  `${import.meta.env.BASE_URL}/images/animals/DSC_0297.JPG`,
  `${import.meta.env.BASE_URL}/images/animals/DSC_0302.JPG`,
  `${import.meta.env.BASE_URL}/images/animals/DSC_0310.JPG`,
  `${import.meta.env.BASE_URL}/images/animals/DSC_0390.JPG`,
  `${import.meta.env.BASE_URL}/images/animals/DSC_0422.JPG`,
  `${import.meta.env.BASE_URL}/images/animals/DSC_0453.JPG`,
  `${import.meta.env.BASE_URL}/images/animals/DSC_0481.JPG`,
  `${import.meta.env.BASE_URL}/images/animals/DSC_0594.JPG`,
  `${import.meta.env.BASE_URL}/images/animals/DSC_0737.JPG`,
  `${import.meta.env.BASE_URL}/images/animals/DSC_0748.JPG`,
  `${import.meta.env.BASE_URL}/images/animals/DSC_0785.JPG`,
  `${import.meta.env.BASE_URL}/images/animals/DSC_0808.JPG`,
  `${import.meta.env.BASE_URL}/images/animals/DSC_0837.JPG`,
  `${import.meta.env.BASE_URL}/images/animals/DSC_0848.JPG`,
  `${import.meta.env.BASE_URL}/images/animals/DSC_0981.JPG`,
  `${import.meta.env.BASE_URL}/images/animals/DSC_1072.JPG`,
  `${import.meta.env.BASE_URL}/images/animals/DSC_1082.JPG`,
  `${import.meta.env.BASE_URL}/images/animals/DSC_1099.JPG`,
  `${import.meta.env.BASE_URL}/images/animals/DSC_1124.JPG`,
  `${import.meta.env.BASE_URL}/images/animals/DSC_1174.JPG`,
  `${import.meta.env.BASE_URL}/images/animals/DSC_1242.JPG`,
  `${import.meta.env.BASE_URL}/images/animals/DSC_1320.JPG`,
  `${import.meta.env.BASE_URL}/images/animals/DSC_1328.JPG`,
  `${import.meta.env.BASE_URL}/images/animals/DSC_1359.JPG`,
  `${import.meta.env.BASE_URL}/images/animals/DSC_1369.JPG`,
  `${import.meta.env.BASE_URL}/images/animals/DSC_1858.JPG`,
  `${import.meta.env.BASE_URL}/images/animals/DSC_1869.JPG`,
  `${import.meta.env.BASE_URL}/images/animals/DSC_1923.JPG`,
  `${import.meta.env.BASE_URL}/images/animals/DSC_1960.JPG`,
  `${import.meta.env.BASE_URL}/images/animals/DSC_1982.JPG`,
  `${import.meta.env.BASE_URL}/images/animals/DSC_2011.JPG`,
  `${import.meta.env.BASE_URL}/images/animals/DSC_2070.JPG`,
  `${import.meta.env.BASE_URL}/images/animals/DSC_2110.JPG`,
  `${import.meta.env.BASE_URL}/images/animals/DSC_2120.JPG`,
  `${import.meta.env.BASE_URL}/images/animals/DSC_2242.JPG`,
  `${import.meta.env.BASE_URL}/images/animals/DSC_2295.JPG`,
  `${import.meta.env.BASE_URL}/images/animals/DSC_2434.JPG`,
  `${import.meta.env.BASE_URL}/images/animals/DSC_2713.JPG`,
  `${import.meta.env.BASE_URL}/images/animals/DSC_4548.JPG`,
  `${import.meta.env.BASE_URL}/images/animals/DSC_4768.JPG`,
  `${import.meta.env.BASE_URL}/images/animals/DSC_6704.JPG`,
  `${import.meta.env.BASE_URL}/images/animals/DSC_7139.JPG`,
  `${import.meta.env.BASE_URL}/images/animals/DSC_7158.JPG`,
  `${import.meta.env.BASE_URL}/images/animals/DSC_7181.JPG`,
  `${import.meta.env.BASE_URL}/images/animals/DSC_8172.JPG`,
  `${import.meta.env.BASE_URL}/images/animals/DSC_8954.JPG`,
  `${import.meta.env.BASE_URL}/images/animals/DSC_9065.JPG`,
  `${import.meta.env.BASE_URL}/images/animals/DSC_9071.JPG`,
  `${import.meta.env.BASE_URL}/images/animals/DSC_9079.JPG`,
  `${import.meta.env.BASE_URL}/images/animals/DSC_9080.JPG`,
  `${import.meta.env.BASE_URL}/images/animals/DSC_9082.JPG`,
  `${import.meta.env.BASE_URL}/images/animals/DSC_9093.JPG`,
  `${import.meta.env.BASE_URL}/images/animals/DSC_9109.JPG`,
  `${import.meta.env.BASE_URL}/images/animals/DSC_9170.JPG`,
  `${import.meta.env.BASE_URL}/images/animals/DSC_9265.JPG`,
];

const Animals = () => {
  return <GalleryTemplate imagePaths={imagePaths} />;
};

export default Animals;
